version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/DSN/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3030:3030"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/DSN/grafana/provisioning/datasources.yml